# Generated by Django 3.0.8 on 2021-01-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_auto_20210119_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_made_in',
            field=models.CharField(default=True, max_length=254),
        ),
    ]
