# Generated by Django 3.0.8 on 2021-01-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_auto_20210119_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_latest_img',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
