# Generated by Django 3.0.8 on 2021-01-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_product_p_latest_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='p_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='p_latest_img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='p_made_in',
        ),
        migrations.RemoveField(
            model_name='product',
            name='p_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
