# Generated by Django 3.0.8 on 2021-01-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_auto_20210130_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_desc',
            field=models.CharField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='p_image',
            field=models.ImageField(default=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='p_latest_img',
            field=models.ImageField(default=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='p_made_in',
            field=models.CharField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='p_price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=True, max_length=200),
        ),
    ]
