# Generated by Django 3.0.8 on 2021-01-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0017_auto_20210130_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_image',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_latest_img',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
