# Generated by Django 3.0.8 on 2021-01-31 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0018_auto_20210130_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_made_in',
        ),
    ]
